// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfowfujvyhjcoygjlsej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmb3dmdWp2eWhqY295Z2psc2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTcwNjgsImV4cCI6MjA2Mzc3MzA2OH0.WDC3SjAuRAeYMRKWQZPcd0MHwyZCi5Ma6SV4f6gW6QI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);